#!/bin/bash

# Helper script to get Railway connection URLs
# This script helps you copy the correct connection strings

echo "================================================="
echo "Railway Connection URL Helper"
echo "================================================="
echo ""
echo "This script will help you get the correct connection URLs from Railway."
echo ""
echo "📋 STEPS TO FOLLOW:"
echo ""
echo "1. Open Railway dashboard: https://railway.app/dashboard"
echo ""
echo "2. Navigate to your 'Meta-Analysis-Tool' project"
echo ""
echo "3. GET POSTGRESQL URL:"
echo "   - Click on your PostgreSQL service"
echo "   - Go to 'Variables' tab"
echo "   - Find 'DATABASE_URL'"
echo "   - Click the copy icon"
echo ""
echo "4. GET REDIS URL:"
echo "   - Click on your Redis service"
echo "   - Go to 'Variables' tab"
echo "   - Find 'REDIS_URL' (might also be called 'REDIS_PRIVATE_URL')"
echo "   - Click the copy icon"
echo ""
echo "5. SET BACKEND ENVIRONMENT VARIABLES:"
echo "   - Click on your backend/main service"
echo "   - Go to 'Variables' tab"
echo "   - REMOVE the variables with ${{...}} syntax if present:"
echo "     • DATABASE_URL"
echo "     • REDIS_URL"
echo "   - ADD NEW RAW variables:"
echo "     • DATABASE_URL = (paste the PostgreSQL URL from step 3)"
echo "     • REDIS_URL = (paste the Redis URL from step 4)"
echo "   - Click 'Save' or 'Add Variable'"
echo ""
echo "6. Railway will automatically redeploy your service"
echo ""
echo "7. Check deployment logs:"
echo "   - Look for 'Application startup complete'"
echo "   - Should NOT see 'Could not parse SQLAlchemy URL' error"
echo ""
echo "================================================="
echo "ALTERNATIVE: Check Service Names"
echo "================================================="
echo ""
echo "If you want to use service references (${{...}}), check:"
echo ""
echo "1. In Railway dashboard, look at your services list"
echo "2. Note the EXACT name of your PostgreSQL service"
echo "   (Could be: Postgres, PostgreSQL, postgres, database, etc.)"
echo "3. Note the EXACT name of your Redis service"
echo "   (Could be: Redis, redis, cache, etc.)"
echo ""
echo "4. Then use these formats:"
echo "   DATABASE_URL=\${{ExactServiceName.DATABASE_URL}}"
echo "   REDIS_URL=\${{ExactServiceName.REDIS_URL}}"
echo ""
echo "================================================="
echo "QUICK CLI METHOD (if project is linked):"
echo "================================================="
echo ""
echo "Run these commands (replace with actual URLs):"
echo ""
echo "railway variables --set DATABASE_URL=\"postgresql://user:pass@host:port/db\""
echo "railway variables --set REDIS_URL=\"redis://default:pass@host:port\""
echo ""
echo "================================================="
echo ""
echo "After following these steps, your deployment should succeed!"
echo ""
