"""Research Proposal model - Tool 2: Research Direction Generator."""

from typing import TYPE_CHECKING
import enum

from sqlalchemy import Column, String, Text, Float, Enum as SQLEnum, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSONB, ARRAY
from sqlalchemy.orm import relationship

from app.db.base import Base
from app.models.base import BaseModel

if TYPE_CHECKING:
    from app.models.project import Project
    from app.models.research_gap import ResearchGap


class ProposalStatus(str, enum.Enum):
    """Research proposal status."""

    DRAFT = "draft"
    REFINED = "refined"
    SUBMITTED = "submitted"
    IN_REVIEW = "in_review"
    FUNDED = "funded"
    REJECTED = "rejected"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"


class ProposalType(str, enum.Enum):
    """Type of research proposal."""

    GRANT_APPLICATION = "grant_application"
    THESIS_PROPOSAL = "thesis_proposal"
    RESEARCH_PLAN = "research_plan"
    PROTOCOL = "protocol"
    CONCEPT_NOTE = "concept_note"


class ResearchProposal(Base, BaseModel):
    """Research proposal generated by AI."""

    __tablename__ = "research_proposals"

    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=True, index=True)
    gap_id = Column(UUID(as_uuid=True), ForeignKey("research_gaps.id"), nullable=True, index=True)

    # Basic information
    title = Column(Text, nullable=False)
    proposal_type = Column(SQLEnum(ProposalType), default=ProposalType.RESEARCH_PLAN, nullable=False)
    status = Column(SQLEnum(ProposalStatus), default=ProposalStatus.DRAFT, nullable=False, index=True)

    # Core content
    research_question = Column(Text, nullable=False)
    background = Column(Text, nullable=True)
    significance = Column(Text, nullable=True)
    innovation = Column(Text, nullable=True)
    methodology = Column(Text, nullable=True)
    expected_outcomes = Column(Text, nullable=True)
    expected_impact = Column(Text, nullable=True)
    timeline = Column(Text, nullable=True)
    budget_overview = Column(Text, nullable=True)

    # Research details
    study_population = Column(String(500), nullable=True)
    intervention = Column(String(500), nullable=True)
    comparator = Column(String(500), nullable=True)
    outcomes = Column(ARRAY(String), nullable=True)
    study_design = Column(String(255), nullable=True)

    # References and citations
    key_references = Column(ARRAY(UUID(as_uuid=True)), nullable=True)  # Paper IDs
    literature_gaps_addressed = Column(ARRAY(String), nullable=True)

    # Scoring and prediction
    novelty_score = Column(Float, nullable=True)  # 0.0 to 1.0
    feasibility_score = Column(Float, nullable=True)  # 0.0 to 1.0
    impact_score = Column(Float, nullable=True)  # 0.0 to 1.0
    predicted_citation_count = Column(Float, nullable=True)
    funding_likelihood = Column(Float, nullable=True)  # 0.0 to 1.0

    # Format-specific content
    nih_format = Column(JSONB, nullable=True, default=dict)
    nsf_format = Column(JSONB, nullable=True, default=dict)
    custom_sections = Column(JSONB, nullable=True, default=dict)

    # AI assistance
    ai_generated = Column(JSONB, default=True, nullable=False)
    generation_prompt = Column(Text, nullable=True)
    refinement_history = Column(JSONB, nullable=True, default=list)

    # Tracking
    submitted_to = Column(String(255), nullable=True)
    submission_date = Column(JSONB, nullable=True)
    decision_date = Column(JSONB, nullable=True)
    decision = Column(String(100), nullable=True)

    # Metadata
    metadata = Column(JSONB, nullable=True, default=dict)

    # Relationships
    project = relationship("Project", foreign_keys=[project_id])
    research_gap = relationship("ResearchGap", foreign_keys=[gap_id])

    def __repr__(self) -> str:
        """String representation."""
        return f"<ResearchProposal(id={self.id}, title={self.title[:50]}..., status={self.status})>"
